
const menuOptions = [
  { label: '会社メニュー', value: 1 },
  { label: '担当者メニュー', value: 2 },
  { label: '活動メニュー', value: 3 },
  { label: '案件メニュー', value: 4 },
];

const companyColumnOptions = [
  { label: "会社ID", value: 1 },
  { label: "会社名", value: 2 },
  { label: "代表TEL", value: 3 },
  { label: "住所", value: 4 },
  { label: "業界", value: 5 },
  { label: "業種", value: 6 },
  { label: "規模ランク", value: 7 },
  { label: "種別", value: 8 },
  { label: "従業員数", value: 9 },
  { label: "地区", value: 10 },
  { label: "都道府県", value: 11 },
  { label: "代表FAX", value: 12 },
  { label: "郵便番号", value: 13 },
  { label: "資本金額(百万円)", value: 14 },
  { label: "決算月", value: 15 },
  { label: "法人番号", value: 16 },
  { label: "売上高", value: 17 },
  { label: "資料禁止", value: 18 },
  { label: "TEL禁止", value: 19 },
  { label: "会社自由使用欄1", value: 20 },
  { label: "会社自由使用欄2", value: 21 },
  { label: "会社自由使用欄3", value: 22 },
  { label: "会社備考", value: 23 }
];

const contactColumnOptions = [
  { label: "担当者ID", value: 1 },
  { label: "会社ID", value: 2 },
  { label: "会社名", value: 3 },
  { label: "担当(姓)", value: 4 },
  { label: "担当(名)", value: 5 },
  { label: "フリガナ", value: 6 },
  { label: "部署名", value: 7 },
  { label: "TEL", value: 8 },
  { label: "携帯電話", value: 9 },
  { label: "Email", value: 10 },
  { label: "役職名", value: 11 },
  { label: "職種", value: 12 },
  { label: "職位", value: 13 },
  { label: "内線", value: 14 },
  { label: "FAX", value: 15 },
  { label: "担当者備考", value: 16 },
  { label: "資料禁止", value: 17 },
  { label: "TEL禁止", value: 18 },
  { label: "TEL注意", value: 19 },
  { label: "フォロー予定", value: 20 },
  { label: "担当者自由使用欄1", value: 21 },
  { label: "担当者自由使用欄2", value: 22 },
  { label: "担当者自由使用欄3", value: 23 },
  { label: "代表FAX", value: 24 },
  { label: "業界", value: 25 },
  { label: "業種", value: 26 },
  { label: "規模ランク", value: 27 },
  { label: "郵便番号", value: 28 },
  { label: "都道府県", value: 29 },
  { label: "地区", value: 30 },
  { label: "住所", value: 31 },
  { label: "種別", value: 32 },
  { label: "法人番号", value: 33 },
  { label: "資本金額(百万円)", value: 34 },
  { label: "従業員数", value: 35 },
  { label: "決算月", value: 36 },
  { label: "売上高", value: 37 },
  { label: "会社自由使用欄1", value: 38 },
  { label: "会社自由使用欄2", value: 39 },
  { label: "会社自由使用欄3", value: 40 },
  { label: "会社備考", value: 41 }
];

const activityColumnOptions = [
  { label: "活動日", value: 1 },
  { label: "活動ID", value: 2 },
  { label: "営業担当", value: 3 },
  { label: "会社ID", value: 4 },
  { label: "会社名", value: 5 },
  { label: "担当者ID", value: 6 },
  { label: "担当(姓)", value: 7 },
  { label: "フリガナ", value: 8 },
  { label: "タイプ", value: 9 },
  { label: "コメント", value: 10 },
  { label: "目的", value: 11 },
  { label: "案件名", value: 12 },
  { label: "担当(名)", value: 13 },
  { label: "動機", value: 14 },
  { label: "案件ID", value: 15 },
  { label: "リードID", value: 16 },
  { label: "アポ", value: 17 },
  { label: "クレーム", value: 18 },
  { label: "開始時刻", value: 19 },
  { label: "終了時刻", value: 20 },
  { label: "活動時間", value: 21 },
  { label: "面談人数", value: 22 },
  { label: "フォロー完了", value: 23 },
  { label: "自由使用欄1", value: 24 },
  { label: "自由使用欄2", value: 25 },
  { label: "自由使用欄3", value: 26 },
  { label: "代表TEL", value: 27 },
  { label: "代表FAX", value: 28 },
  { label: "郵便番号", value: 29 },
  { label: "都道府県", value: 30 },
  { label: "地区", value: 31 },
  { label: "住所", value: 32 },
  { label: "業界", value: 33 },
  { label: "業種", value: 34 },
  { label: "規模ランク", value: 35 },
  { label: "種別", value: 36 },
  { label: "法人番号", value: 37 },
  { label: "資本金額(百万円)", value: 38 },
  { label: "従業員数", value: 39 },
  { label: "決算月", value: 40 },
  { label: "売上高", value: 41 },
  { label: "資料禁止", value: 42 },
  { label: "TEL禁止", value: 43 },
  { label: "会社自由使用欄1", value: 44 },
  { label: "会社自由使用欄2", value: 45 },
  { label: "会社自由使用欄3", value: 46 },
  { label: "会社備考", value: 47 },
  { label: "部署名", value: 48 },
  { label: "TEL", value: 49 },
  { label: "内線", value: 50 },
  { label: "FAX", value: 51 },
  { label: "携帯電話", value: 52 },
  { label: "Email", value: 53 },
  { label: "職種", value: 54 },
  { label: "職位", value: 55 },
  { label: "役職名", value: 56 },
  { label: "TEL禁止", value: 57 },
  { label: "TEL注意", value: 58 },
  { label: "担当者自由使用欄1", value: 59 },
  { label: "担当者自由使用欄2", value: 60 },
  { label: "担当者自由使用欄3", value: 61 },
  { label: "担当者備考", value: 62 },
  { label: "自由使用欄7", value: 63 },
  { label: "自由使用欄6", value: 64 },
  { label: "自由使用欄5", value: 65 },
  { label: "自由使用欄4", value: 66 }
];

const projectColumnOptions = [
  { label: "話題日", value: 1 },
  { label: "売上日", value: 2 },
  { label: "フォロー予定", value: 3 },
  { label: "案件ステータス", value: 4 },
  { label: "営業担当", value: 5 },
  { label: "案件ID", value: 6 },
  { label: "案件名", value: 7 },
  { label: "会社ID", value: 8 },
  { label: "会社名", value: 9 },
  { label: "担当者ID", value: 10 },
  { label: "担当(姓)", value: 11 },
  { label: "担当(名)", value: 12 },
  { label: "フリガナ", value: 13 },
  { label: "案件概要", value: 14 },
  { label: "当初確度", value: 15 },
  { label: "見直確度", value: 16 },
  { label: "競合会社", value: 17 },
  { label: "発生動機", value: 18 },
  { label: "引合手段", value: 19 },
  { label: "ステージ1", value: 20 },
  { label: "ステージ3", value: 21 },
  { label: "ステージ4", value: 22 },
  { label: "予定機種", value: 23 },
  { label: "予定台数", value: 24 },
  { label: "予定時期", value: 25 },
  { label: "予定売上", value: 26 },
  { label: "実績機種", value: 27 },
  { label: "実績台数", value: 28 },
  { label: "実績売上時期", value: 29 },
  { label: "実績売上", value: 30 },
  { label: "案件化日", value: 31 },
  { label: "受注日", value: 32 },
  { label: "失注日", value: 33 },
  { label: "ステージ2", value: 34 },
  { label: "自由使用欄1", value: 35 },
  { label: "自由使用欄2", value: 36 },
  { label: "自由使用欄3", value: 37 },
  { label: "代表TEL", value: 38 },
  { label: "代表FAX", value: 39 },
  { label: "郵便番号", value: 40 },
  { label: "都道府県", value: 41 },
  { label: "地区", value: 42 },
  { label: "住所", value: 43 },
  { label: "業界", value: 44 },
  { label: "業種", value: 45 },
  { label: "規模ランク", value: 46 },
  { label: "種別", value: 47 },
  { label: "法人番号", value: 48 },
  { label: "資本金額(百万円)", value: 49 },
  { label: "従業員数", value: 50 },
  { label: "決算月", value: 51 },
  { label: "売上高", value: 52 },
  { label: "資料禁止", value: 53 },
  { label: "TEL禁止", value: 54 },
  { label: "会社自由使用欄1", value: 55 },
  { label: "会社自由使用欄2", value: 56 },
  { label: "会社自由使用欄3", value: 57 },
  { label: "会社備考", value: 58 },
  { label: "部署名", value: 59 },
  { label: "TEL", value: 60 },
  { label: "内線", value: 61 },
  { label: "FAX", value: 62 },
  { label: "携帯電話", value: 63 },
  { label: "Email", value: 64 },
  { label: "職種", value: 65 },
  { label: "職位", value: 66 },
  { label: "役職名", value: 67 },
  { label: "TEL禁止フラグ", value: 68 },
  { label: "TEL注意フラグ", value: 69 },
  { label: "担当者自由使用欄1", value: 70 },
  { label: "担当者自由使用欄2", value: 71 },
  { label: "担当者自由使用欄3", value: 72 },
  { label: "担当者備考", value: 73 }
];

const subMenuOptions = {
  1: [
    { label: '会社一覧', value: 1, columns: companyColumnOptions },
    { label: '担当者一覧', value: 2, columns: contactColumnOptions },
    { label: '活動一覧', value: 3, columns: activityColumnOptions },
    { label: '案件一覧', value: 4, columns: projectColumnOptions },
  ],
  2: [
    { label: '担当者一覧', value: 1, columns: contactColumnOptions },
    { label: '活動一覧', value: 2, columns: activityColumnOptions },
    { label: '案件一覧', value: 3, columns: projectColumnOptions },
  ],
  3: [
    { label: '活動一覧', value: 1, columns: activityColumnOptions },
  ],
  4: [
    { label: '案件一覧', value: 1, columns: projectColumnOptions },
    { label: '活動一覧', value: 2, columns: activityColumnOptions },
  ],
};

export { menuOptions, subMenuOptions, companyColumnOptions, contactColumnOptions, activityColumnOptions, projectColumnOptions };
